const $ = s => document.querySelector(s);
const {symbols,starter,makeRound}=GardenData;
let prefs={scope:'starter',sound:true,voice:''}, progress={flowers:0,rounds:0}, storageOK=true;
try { Object.assign(prefs,JSON.parse(localStorage.getItem('garden-prefs')||'{}')); Object.assign(progress,JSON.parse(localStorage.getItem('garden-progress')||'{}')); } catch {storageOK=false;}
if(!['starter','all'].includes(prefs.scope))prefs.scope='starter';
if(!Number.isFinite(progress.flowers)||progress.flowers<0)progress.flowers=0;
if(!Number.isFinite(progress.rounds)||progress.rounds<0)progress.rounds=0;
let game=null,voices=[],speakingId=0;
function save(){try{localStorage.setItem('garden-prefs',JSON.stringify(prefs));localStorage.setItem('garden-progress',JSON.stringify(progress));}catch{storageOK=false;}}
function stopSpeech(){speakingId++;if('speechSynthesis' in window)speechSynthesis.cancel();}
function speak(text){
 if(!prefs.sound)return;
 if(!('speechSynthesis' in window)||!voices.length){const el=$('#audio-note');if(el)el.textContent='這台裝置沒有中文朗讀，請大人陪你念一念。';return;}
 stopSpeech();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.78;u.voice=voices.find(v=>v.voiceURI===prefs.voice)||voices.find(v=>/zh[-_]TW/i.test(v.lang))||voices[0];
 u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error)){const el=$('#audio-note');if(el)el.textContent='聲音暫時無法播放，請大人陪你念題目。';}};speechSynthesis.speak(u);
}
function updateVoices(){voices=('speechSynthesis' in window?speechSynthesis.getVoices():[]).filter(v=>/^zh|cmn/i.test(v.lang));$('#voice').replaceChildren();if(!voices.length){$('#voice').add(new Option('沒有中文語音：請大人讀題',''));}else{voices.forEach(v=>$('#voice').add(new Option(v.name+' · '+v.lang,v.voiceURI)));$('#voice').value=voices.some(v=>v.voiceURI===prefs.voice)?prefs.voice:(voices.find(v=>/zh[-_]TW/i.test(v.lang))||voices[0]).voiceURI;}}
const art=`<svg viewBox="0 0 520 370" role="img" aria-label="小兔子陪你在花園認識注音"><ellipse cx="260" cy="316" rx="226" ry="31" fill="#d8e9b9"/><path d="M55 307Q84 246 146 288Q231 240 302 282Q407 237 471 308" fill="#c4dfa0"/><circle cx="428" cy="61" r="31" fill="#f6d97b"/><g fill="#fff" opacity=".9"><ellipse cx="117" cy="80" rx="44" ry="15"/><circle cx="110" cy="68" r="20"/><ellipse cx="348" cy="103" rx="38" ry="12"/><circle cx="344" cy="93" r="16"/></g><g transform="rotate(-12 144 205)"><rect x="66" y="152" width="112" height="119" rx="24" fill="#fff4d6" stroke="#e5c67d" stroke-width="3"/><text x="122" y="235" text-anchor="middle" font-size="66" fill="#b17a35">ㄅ</text></g><g transform="rotate(12 374 187)"><rect x="337" y="131" width="106" height="113" rx="23" fill="#e5efef" stroke="#95c5c6" stroke-width="3"/><text x="390" y="210" text-anchor="middle" font-size="65" fill="#47888a">ㄚ</text></g><ellipse cx="260" cy="258" rx="65" ry="60" fill="#faf6ed"/><ellipse cx="232" cy="124" rx="18" ry="70" transform="rotate(-13 232 124)" fill="#faf6ed"/><ellipse cx="285" cy="120" rx="18" ry="70" transform="rotate(10 285 120)" fill="#faf6ed"/><ellipse cx="232" cy="122" rx="8" ry="51" transform="rotate(-13 232 122)" fill="#efc6b8"/><ellipse cx="285" cy="118" rx="8" ry="51" transform="rotate(10 285 118)" fill="#efc6b8"/><ellipse cx="261" cy="197" rx="69" ry="60" fill="#fffaf0"/><circle cx="237" cy="191" r="5" fill="#574b3f"/><circle cx="285" cy="191" r="5" fill="#574b3f"/><ellipse cx="220" cy="210" rx="13" ry="8" fill="#f3c5b4"/><ellipse cx="302" cy="210" rx="13" ry="8" fill="#f3c5b4"/><path d="M255 203Q261 211 267 203M261 209V217M249 216Q261 229 273 216" fill="none" stroke="#79574c" stroke-width="3" stroke-linecap="round"/><path d="M238 257Q261 246 284 257L280 285H242Z" fill="#94b898"/><ellipse cx="227" cy="303" rx="25" ry="13" fill="#fffaf0"/><ellipse cx="290" cy="303" rx="25" ry="13" fill="#fffaf0"/><g stroke="#759b64" stroke-width="5"><path d="M68 316V280M441 315V279"/></g><g fill="#e9a28f"><circle cx="68" cy="266" r="9"/><circle cx="54" cy="280" r="9"/><circle cx="82" cy="280" r="9"/><circle cx="68" cy="293" r="9"/></g><circle cx="68" cy="280" r="7" fill="#f6d97b"/><g fill="#f4d678"><circle cx="441" cy="265" r="9"/><circle cx="427" cy="279" r="9"/><circle cx="455" cy="279" r="9"/><circle cx="441" cy="293" r="9"/></g><circle cx="441" cy="279" r="7" fill="#aa8050"/></svg>`;
function home(){window.scrollTo(0,0);stopSpeech();game=null;$('#app').innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span> 給小小探險家的聲音遊樂場</div><h1>聽見聲音，<br>讓注音<span class="accent">開花。</span></h1><p>和小兔一起找一找、聽一聽、拼一拼。<br>每天一點點，發現注音的樂趣。</p><div class="hero-tags"><span>🌱 從認識開始</span><span>👋 大人陪我玩</span><span>✨ 慢慢來也很好</span></div></div><div class="hero-art">${art}<span class="art-tag">你好！一起來玩吧</span></div></section><section class="play-section"><div class="section-title"><div><span class="eyebrow">LET’S PLAY</span><h2>今天想玩什麼？</h2></div><span class="collection">✿ 已種下 <b>${progress.flowers}</b> 朵小花</span></div><div class="game-cards"><button class="game-card peach" data-mode="match"><span class="card-top"><span class="level">01 · 初次見面</span><span>↗</span></span><span class="card-art symbol-art"><i>ㄅ</i><i>ㄅ</i><small>✦</small></span><strong>找找注音</strong><span class="card-desc">看一看，找出一樣的注音朋友。</span><span class="card-bottom">認識字形 <span>開始玩 →</span></span></button><button class="game-card mint" data-mode="listen"><span class="card-top"><span class="level">02 · 聲音朋友</span><span>↗</span></span><span class="card-art">🐱<span class="sound-bubble">♫</span></span><strong>聽聽找朋友</strong><span class="card-desc">聽生活詞，找出開頭的注音。</span><span class="card-bottom">聲音與符號 <span>開始玩 →</span></span></button><button class="game-card lilac" data-mode="build"><span class="card-top"><span class="level">03 · 一起拼拼看</span><span>↗</span></span><span class="card-art train-art"><i>ㄇ</i><span>＋</span><i>ㄠ</i></span><strong>注音小火車</strong><span class="card-desc">照著提示，把注音排成一個詞。</span><span class="card-bottom">引導式拼音 <span>開始玩 →</span></span></button></div></section><section class="parent-strip"><span>🌼</span><div><strong>小花園的約定：每個孩子都有自己的步調。</strong><p>每回合只有 5 題。不倒數、不扣分，答錯了就一起再試試。</p></div><button id="tips">看看親子玩法 →</button></section>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('#tips').onclick=openSettings;}
function start(mode){stopSpeech();game={mode,questions:makeRound(mode,prefs.scope),index:0,done:false,selected:[],used:[],attempts:0,firstTry:0};renderGame();}
function questionSpeech(q){return game.mode==='listen'?`聽一聽。${q.word}。${q.word}。找出${q.word}開頭的注音。`:`${q.word}。一起拼出${q.word}。`;}
function renderGame(){
 window.scrollTo(0,0);
 const q=game.questions[game.index], mode=game.mode;
 const names={match:'找找注音',listen:'聽聽找朋友',build:'注音小火車'};
 $('#app').innerHTML=`<section class="game-panel"><div class="game-heading"><button id="back" class="quiet">← 回到花園</button><span>${names[mode]}</span><span>${game.index+1} / 5</span></div><div class="step-dots" aria-label="第 ${game.index+1} 題，共 5 題">${game.questions.map((_,i)=>`<span class="${i<game.index?'finished':i===game.index?'current':''}">${i<game.index?'✿':i+1}</span>`).join('')}</div><h1 class="question-title">${mode==='match'?'哪一個和我一樣？':mode==='listen'?'聽一聽，找開頭的注音':'讓注音朋友坐上小火車'}</h1><p class="question-sub">${mode==='match'?'看上面的符號，再點下面一樣的朋友。':mode==='listen'?'按喇叭聽詞語，再點一個注音朋友。':'照著提示，依序點選下面的注音。'}</p><div class="target ${mode==='match'?'symbol-target':''}">${mode==='match'?q.answer:`<span class="word-picture" role="img" aria-label="${q.word}">${q.emoji}</span><span class="word-label">${q.word}</span>`}</div>${mode==='match'?'':`<button id="replay" class="replay">♫ 聽一聽「${q.word}」</button><p id="audio-note" class="audio-note">${!prefs.sound?'聲音已關閉，請大人陪你念題目。':voices.length?'可以重聽，也可以跟著大人說一遍。':'請大人讀出「'+q.word+'」，或使用有中文語音的裝置。'}</p>`}${mode==='build'?`<div class="train-hint">拼音小提示：<b>${q.zhuyin}</b> <span>聲調已經幫你放好了</span></div><div class="train" aria-label="拼音位置">${q.parts.map((_,i)=>`<div class="carriage" id="slot-${i}">？</div>`).join('')}<span class="tone">${q.tone||'一聲'}</span></div>`:''}<div class="choices">${q.options.map((s,i)=>`<button class="choice" data-index="${i}" aria-label="選擇 ${s}">${s}</button>`).join('')}</div><div id="feedback" class="feedback" role="status" aria-live="polite">慢慢找，你可以的！</div><div class="game-actions">${mode==='build'?'<button id="undo" class="quiet">↶ 重新排一次</button>':''}<button id="next" class="primary" hidden>${game.index===4?'看看我的小花園 ✿':'下一個朋友 →'}</button></div></section>`;
 $('#back').onclick=home;document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.index),b));if($('#replay'))$('#replay').onclick=()=>speak(questionSpeech(q));if($('#undo'))$('#undo').onclick=()=>{game.selected=[];game.used=[];renderGame();};$('#next').onclick=next;
}
function answer(index,button){
 if(game.done)return;const q=game.questions[game.index];game.attempts++;
 if(game.mode==='build'){
  if(game.used.includes(index))return;
  const position=game.selected.length;
  if(q.options[index]!==q.parts[position]){retry(button,`這節車廂等的是 ${q.parts[position]}，再找找看。`);return;}
  game.selected.push(q.options[index]);game.used.push(index);button.disabled=true;button.classList.add('correct');$('#slot-'+position).textContent=q.options[index];
  if(game.selected.length<q.parts.length){$('#feedback').textContent='第一個朋友上車了，再找下一個！';return;}
 }else if(q.options[index]!==q.answer){retry(button,'還沒找到，再看一看、聽一聽。');return;}else{button.classList.add('correct');}
 game.done=true;if(game.attempts===(game.mode==='build'?q.parts.length:1))game.firstTry++;
 document.querySelectorAll('[data-index]').forEach(b=>b.disabled=true);$('#feedback').classList.add('success');$('#feedback').textContent=game.mode==='build'?`✿ 拼好了！${q.zhuyin}，${q.word}！`:'✿ 找到了！一朵小花為你開了。';$('#next').hidden=false;$('#next').focus();if($('#undo'))$('#undo').hidden=true;if(game.mode==='build')speak(q.word);
}
function retry(button,message){button.classList.remove('wiggle');void button.offsetWidth;button.classList.add('wiggle');$('#feedback').textContent=message;}
function next(){if(!game.done)return;stopSpeech();if(game.index===4){progress.flowers+=5;progress.rounds++;save();finish();}else{game.index++;game.done=false;game.attempts=0;game.selected=[];game.used=[];renderGame();}}
function finish(){window.scrollTo(0,0);const mode=game.mode;$('#app').innerHTML=`<section class="finish"><div class="eyebrow">每一次嘗試，都在長大</div><div class="finish-flowers">🌷 🌼 🌷 🌼 🌷</div><h1>小花園又開花了！</h1><p>你和 5 個注音朋友一起玩過了。<br>伸個懶腰，和大人說說你最喜歡哪一個吧。</p><div class="finish-count">✿ 這次種下 5 朵小花 · 累積 ${progress.flowers} 朵</div><div class="finish-actions"><button class="primary" id="rest">回到花園，休息一下</button><button class="quiet" id="again">再玩一回合 →</button></div><p class="note">花朵記錄參與，不代表精熟程度。</p></section>`;$('#rest').onclick=home;$('#again').onclick=()=>start(mode);}
function openSettings(){$('#scope').value=prefs.scope;updateVoices();$('#storage-note').textContent=storageOK?'設定與花朵只保存在這台裝置，不上傳資料。':'瀏覽器無法保存紀錄，仍可正常玩遊戲。';$('#settings').showModal();}
$('#brand').onclick=e=>{e.preventDefault();home();};$('#parent').onclick=openSettings;$('#close-settings').onclick=()=>$('#settings').close();$('#scope').onchange=e=>{prefs.scope=e.target.value;save();};$('#voice').onchange=e=>{prefs.voice=e.target.value;save();};$('#reset-progress').onclick=()=>{if(!confirm('清除這台裝置累積的花朵紀錄？'))return;progress={flowers:0,rounds:0};save();$('#storage-note').textContent='花朵紀錄已清除。';if(!game)home();};
function soundLabel(){$('#sound').textContent=prefs.sound?'♫ 聲音開啟':'♫ 聲音關閉';$('#sound').setAttribute('aria-pressed',String(prefs.sound));}
$('#sound').onclick=()=>{prefs.sound=!prefs.sound;stopSpeech();save();soundLabel();if(game&&!game.done&&$('#audio-note'))$('#audio-note').textContent=prefs.sound?'按「聽一聽」播放詞語。':'聲音已關閉，請大人陪你念題目。';};
if('speechSynthesis'in window)speechSynthesis.addEventListener('voiceschanged',updateVoices);updateVoices();soundLabel();home();
