(function(root){
  'use strict';
  function open({progress,save,speak,effect,home,start,storageOK,heading,music},initial=null){
    const G=root.GardenLayout,app=document.querySelector('#app'),find=s=>app.querySelector(s);
    progress.garden=G.restore(progress,progress.rounds);
    progress.gardenZones={pond:G.restore({garden:progress.gardenZones?.pond||[]},progress.rounds,'pond'),picnic:G.restore({garden:progress.gardenZones?.picnic||[]},progress.rounds,'picnic')};
    progress.gardenAlbum=G.restoreAlbum(progress.gardenAlbum,progress.rounds);progress.gardenMemories=G.milestones([],progress.gardenMemories||[]);
    let area=Object.hasOwn(G.areas,progress.gardenArea)?progress.gardenArea:'meadow';
    if(initial&&G.kinds[initial]?.areas&&!G.kinds[initial].areas.includes(area))area=G.kinds[initial].areas[0];
    let selected=G.kinds[initial]?.at<=progress.rounds?initial:null,category=G.kinds[selected]?.category||'plants',moving=null,active=null,viewing=false,undo=null,photoUndo=null,drag=null,suppressClick=0;
    const memoryNames={plant:'親手種下一朵花',animal:'邀請第一位動物朋友',variety:'三種朋友一起住',photo:'留下第一張花園照片',pondvisit:'池塘住進新朋友'};
    const items=()=>area==='meadow'?progress.garden:progress.gardenZones[area];
    const setItems=value=>{if(area==='meadow')progress.garden=value;else progress.gardenZones[area]=value;};
    app.innerHTML=`<section class="garden-page garden-studio">${heading('我的花園',progress.rounds,'回合')}<div class="garden-title"><div><h1>我的小天地</h1><p>選朋友點亮點，也可以拖過來放。</p></div><button id="garden-view" class="quiet" aria-pressed="false">✦ 欣賞花園</button></div><div class="garden-regions" role="group" aria-label="花園區域">${Object.entries(G.areas).map(([id,d])=>`<button data-area="${id}" aria-pressed="${area===id}">${d.emoji} ${d.name}</button>`).join('')}</div><div class="garden-weather" role="group" aria-label="選擇花園天氣">${root.GardenPlay.scenes.map(s=>`<button data-weather="${s.id}" aria-pressed="${s.id===progress.weather}">${s.emoji} ${s.name}</button>`).join('')}</div><div class="garden-scene garden-canvas ${progress.weather}" role="group" aria-label="我的插畫花園"><div id="garden-background"></div><span class="garden-sun" aria-hidden="true"></span><span class="garden-stars" aria-hidden="true">✦　✧　✦</span><div id="garden-objects"></div><div id="garden-spots"></div><span id="garden-bubble" class="garden-bubble" role="status" hidden></span><span class="garden-sign" aria-hidden="true"></span></div><div id="garden-summary" class="garden-summary"></div><p id="garden-message" class="garden-instruction" role="status"></p><div id="garden-controls"><div class="garden-tools"><button id="garden-cancel" class="quiet" hidden>放回工具箱</button><button id="garden-undo" class="quiet" disabled>↶ 復原</button><div id="garden-object-actions" hidden><button id="garden-move" class="quiet">搬家</button><button id="garden-remove" class="quiet">收回工具箱</button><button id="garden-care" class="quiet">陪朋友玩</button><button id="garden-listen" class="quiet">♫ 聽名字</button></div></div><div class="garden-category" role="group" aria-label="朋友種類">${[['plants','花草'],['animals','動物'],['decor','裝飾']].map(([id,name])=>`<button data-category="${id}" aria-pressed="${id===category}">${name}</button>`).join('')}</div><div id="garden-palette" class="garden-palette" aria-label="選擇花園朋友"></div><p class="garden-tool-note">拖到亮點就會放好；沒放成功，朋友會回原位。解鎖後可一直放。</p></div><div class="garden-photo-tools"><button id="garden-photo" class="quiet">📷 拍張花園照</button><button id="garden-album" class="quiet" aria-expanded="false">▧ 花園相簿</button><button id="garden-ripple" class="quiet" hidden>💧 和池塘玩水</button></div><section id="garden-photo-panel" class="garden-photo-panel" hidden aria-label="花園相簿"><h2>我的花園相簿</h2><p>記下當時的朋友、天氣和位置。相簿只保存在這台裝置，最多 12 張。</p><button id="garden-photo-undo" class="quiet" hidden>↶ 復原收起的照片</button><div id="garden-photo-grid"></div><p id="garden-photo-message" role="status"></p></section><div id="garden-memories" class="badge-shelf" aria-label="我的布置紀念"></div><p id="garden-storage" class="note"></p><button id="garden-play" class="primary">🐰 和小兔去探險</button></section>`;
    const canvas=find('.garden-canvas'),panel=find('.garden-studio');
    if(music){find('#garden-storage').insertAdjacentHTML('afterend',`<div class="garden-music"><label for="garden-track">花園音樂</label><select id="garden-track">${Object.entries(root.GardenSongs).map(([id,s])=>`<option value="${id}">${s.name}</option>`).join('')}</select><button id="garden-music-toggle" class="quiet">播放音樂</button><button id="garden-music-next" class="quiet">下一首</button></div><p id="garden-music-status" class="garden-music-status" role="status"></p><a class="garden-music-credit" href="CREDITS.md" target="_blank" rel="noopener">音樂作者與開放授權 ↗</a>`);find('#garden-track').value=music.track();find('#garden-track').onchange=e=>music.choose(e.target.value);find('#garden-music-toggle').onclick=music.toggle;find('#garden-music-next').onclick=music.next;music.refresh();}
    function showWorkspace(){if(window.matchMedia('(max-width:600px)').matches)window.scrollTo(0,Math.max(0,canvas.getBoundingClientRect().top+window.scrollY-12));}
    function announce(text){find('#garden-message').textContent=text;}
    function syncStatus(){const s=G.stats(items());find('#garden-summary').textContent=`${G.areas[area].name}：${s.plants} 株花草、${s.animals} 位動物朋友${s.types>=3?'，大家一起住！':'。'}`;find('#garden-memories').innerHTML=progress.gardenMemories.map(id=>`<span>✿ ${memoryNames[id]}</span>`).join('');find('#garden-storage').textContent=storageOK()?'三個區域與相簿會自動保存在這台裝置。':'瀏覽器暫時無法保存；離開或重新整理後，布置與照片可能不會留下。';find('#garden-album').textContent=`▧ 花園相簿 ${progress.gardenAlbum.length} / 12`;}
    function drawBackground(){canvas.dataset.area=area;canvas.classList.remove('sunny','sunset','night');canvas.classList.add(progress.weather);find('#garden-background').innerHTML=G.landscape(area);find('.garden-sign').textContent=G.areas[area].name;find('.garden-sun').textContent=root.GardenPlay.scenes.find(s=>s.id===progress.weather).emoji;app.querySelectorAll('[data-area]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.area===area)));app.querySelectorAll('[data-weather]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.weather===progress.weather)));find('#garden-ripple').hidden=area!=='pond';progress.gardenArea=area;}
    function drawObjects(animated=null){
      const container=find('#garden-objects');container.querySelectorAll('[data-object]').forEach(b=>{const p=items().find(p=>p.slot===Number(b.dataset.object));if(!p||p.kind!==b.dataset.kind)b.remove();});
      for(const p of items()){let b=container.querySelector(`[data-object="${p.slot}"]`);if(!b){b=document.createElement('button');b.type='button';b.dataset.object=p.slot;b.dataset.kind=p.kind;b.innerHTML=`<span class="garden-object-shadow"></span><span class="garden-object-art">${G.sprite(p.kind)}</span>`;container.append(b);}const a=G.anchors[p.slot];b.style.left=a.x+'%';b.style.top=a.y+'%';b.style.zIndex=Math.round(a.y/3);b.className=`garden-object kind-${p.kind}${active===p.slot?' chosen':''}${moving===p.slot?' moving':''}${animated===p.slot?' arrived':''}`;b.setAttribute('aria-label',G.kinds[p.kind].name+'，點一下認識或搬家');b.setAttribute('aria-pressed',String(active===p.slot));}syncStatus();
    }
    function drawSpots(){find('#garden-spots').innerHTML=selected&&!viewing?G.anchors.map((a,i)=>G.place(items(),selected,i,progress.rounds,moving,area).ok?`<button class="garden-spot" data-slot="${i}" style="left:${a.x}%;top:${a.y}%" aria-label="${moving===null?'放下':'搬來'}${G.kinds[selected].name}，位置 ${i+1}"><span class="garden-ghost">${G.sprite(selected)}</span><span class="spot-plus" aria-hidden="true">＋</span></button>`:'').join(''):'';find('#garden-cancel').hidden=!selected;find('#garden-object-actions').hidden=active===null||selected!==null;find('#garden-undo').disabled=!undo;const d=items().find(p=>p.slot===active);find('#garden-care').textContent=d&&G.kinds[d.kind].category==='plants'?'💧 澆澆水':d&&G.kinds[d.kind].category==='animals'?'♡ 餵一餵':'✦ 看看裝飾';}
    function drawPalette(){find('#garden-palette').innerHTML=Object.entries(G.kinds).filter(([,d])=>d.category===category&&(!d.areas||d.areas.includes(area))).sort((a,b)=>Number(a[1].at>progress.rounds)-Number(b[1].at>progress.rounds)||Number(!a[1].areas)-Number(!b[1].areas)).map(([id,d])=>`<button data-decoration="${id}" aria-pressed="${selected===id}" ${d.at>progress.rounds?'disabled':''} aria-label="${d.name}${d.at>progress.rounds?'，玩過 '+d.at+' 回合後來訪':''}">${G.sprite(id)}<strong>${d.name}</strong>${d.at>progress.rounds?`<small>${d.at} 回合來訪</small>`:'<small>點選或拖曳</small>'}</button>`).join('');app.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));}
    function clearSelection(){selected=null;moving=null;active=null;drawObjects();drawSpots();drawPalette();find('#garden-bubble').hidden=true;}
    function remember(){undo={garden:progress.garden.map(p=>({...p})),zones:Object.fromEntries(Object.entries(progress.gardenZones).map(([id,list])=>[id,list.map(p=>({...p}))])),memories:[...progress.gardenMemories],weather:progress.weather,area};}
    function commit(animated){const old=[...progress.gardenMemories];progress.gardenMemories=G.milestones(items(),old,items().find(p=>p.slot===animated)?.kind);if(area==='pond'&&!progress.gardenMemories.includes('pondvisit'))progress.gardenMemories.push('pondvisit');save();drawObjects(animated);drawSpots();const added=progress.gardenMemories.filter(id=>!old.includes(id));return added.length?' ✿ '+added.map(id=>memoryNames[id]).join('、')+'！':'';}
    function put(slot){const kind=selected,result=G.place(items(),kind,slot,progress.rounds,moving,area);if(!result.ok){announce('這裡放不下，請選另一個亮點。');return false;}const wasMoving=moving!==null;remember();setItems(result.items);selected=null;moving=null;active=null;find('#garden-bubble').hidden=true;drawPalette();const reward=commit(slot);effect('blossom');announce(G.kinds[kind].name+(wasMoving?'搬到新家了！':'住進你的'+G.areas[area].name+'了！')+reward);find(`[data-object="${slot}"]`).focus({preventScroll:true});return true;}
    function greet(b){active=Number(b.dataset.object);const kind=b.dataset.kind;drawObjects();drawSpots();find('#garden-bubble').hidden=false;find('#garden-bubble').textContent=G.kinds[kind].name+' · '+G.kinds[kind].zhuyin;speak(G.kinds[kind].name);b.classList.remove('greeting');void b.offsetWidth;b.classList.add('greeting');announce(viewing?'你好，'+G.kinds[kind].name+'！':G.kinds[kind].name+'想跟你打招呼！可以搬家、陪它玩或收回。');}
    function drawAlbum(){find('#garden-photo-grid').innerHTML=progress.gardenAlbum.map((photo,i)=>`<article class="garden-photo-card"><div class="garden-photo-picture" role="img" aria-label="第 ${i+1} 張，${G.areas[photo.area].name}的${root.GardenPlay.scenes.find(s=>s.id===photo.weather).name}照片">${G.picture(photo)}</div><h3>第 ${i+1} 張 · ${G.areas[photo.area].name}</h3><p>${new Date(photo.at).toLocaleDateString('zh-TW')} · ${root.GardenPlay.scenes.find(s=>s.id===photo.weather).name} · ${photo.items.length} 位朋友</p><div><button data-photo-load="${i}" class="quiet">照著這張布置</button><button data-photo-download="${i}" class="quiet">下載圖片</button><button data-photo-remove="${i}" class="quiet">收起這張</button></div></article>`).join('')||'<p class="garden-photo-empty">花園準備好了嗎？按「拍張花園照」，留下第一張作品。</p>';find('#garden-photo-undo').hidden=!photoUndo;}
    async function downloadPhoto(photo){const url=URL.createObjectURL(new Blob([G.picture(photo)],{type:'image/svg+xml;charset=utf-8'}));try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const output=document.createElement('canvas');output.width=1200;output.height=750;output.getContext('2d').drawImage(image,0,0,1200,750);const blob=await new Promise(resolve=>output.toBlob(resolve,'image/png'));if(!blob)throw new Error('No image');const fileURL=URL.createObjectURL(blob),link=document.createElement('a');link.href=fileURL;link.download=G.areas[photo.area].name+'-'+photo.at+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(fileURL),3000);find('#garden-photo-message').textContent='圖片已準備下載，可以跟大人一起欣賞。';}catch{find('#garden-photo-message').textContent='這個瀏覽器暫時無法下載圖片，照片仍在相簿裡。';}finally{URL.revokeObjectURL(url);}}
    find('#back').onclick=home;find('#garden-play').onclick=()=>start('adventure');
    panel.addEventListener('click',e=>{
      const b=e.target.closest('button');if(!b)return;if(performance.now()<suppressClick&&b.matches('[data-decoration],[data-object],[data-slot]'))return;
      if(b.dataset.area){area=b.dataset.area;drawBackground();clearSelection();save();announce('來到'+G.areas[area].name+'！這裡的布置會另外保存。');return;}
      if(b.dataset.weather){progress.weather=b.dataset.weather;drawBackground();save();effect('tap');return;}
      if(b.dataset.category){category=b.dataset.category;clearSelection();announce('選個'+({plants:'花草',animals:'動物朋友',decor:'裝飾'}[category])+'，再點亮點，或拖進場景。');return;}
      if(b.dataset.decoration){selected=b.dataset.decoration;moving=null;active=null;drawObjects();drawPalette();drawSpots();announce(find('[data-slot]')?'拿著：'+G.kinds[selected].name+'。點亮點，或把它拖過來。':'適合這位朋友的位置已住滿！先放回工具箱，收回一位朋友，再請它來。');find(`[data-decoration="${selected}"]`).focus({preventScroll:true});showWorkspace();effect('tap');return;}
      if(b.dataset.slot!==undefined&&selected){put(Number(b.dataset.slot));return;}
      if(b.dataset.object!==undefined){if(selected){announce('這裡有朋友了，請點空的亮點。');return;}greet(b);return;}
      if(b.dataset.photoLoad!==undefined){const photo=progress.gardenAlbum[Number(b.dataset.photoLoad)];if(!photo)return;remember();area=photo.area;setItems(photo.items.map(p=>({...p})));progress.weather=photo.weather;viewing=false;find('#garden-controls').hidden=false;find('#garden-view').textContent='✦ 欣賞花園';find('#garden-view').setAttribute('aria-pressed','false');canvas.classList.remove('admiring');drawBackground();clearSelection();save();announce('照著照片布置好了！不喜歡的話，可以按「復原」。');showWorkspace();return;}
      if(b.dataset.photoDownload!==undefined){const photo=progress.gardenAlbum[Number(b.dataset.photoDownload)];if(photo)downloadPhoto(photo);return;}
      if(b.dataset.photoRemove!==undefined){photoUndo={photo:progress.gardenAlbum[Number(b.dataset.photoRemove)],index:Number(b.dataset.photoRemove)};progress.gardenAlbum=progress.gardenAlbum.filter((_,i)=>i!==Number(b.dataset.photoRemove));save();drawAlbum();syncStatus();find('#garden-photo-message').textContent='照片收起來了，按「復原收起的照片」可以放回。';return;}
    });
    find('#garden-cancel').onclick=()=>{clearSelection();announce('朋友放回工具箱了。想放誰，再選一次就好。');};
    find('#garden-move').onclick=()=>{const p=items().find(p=>p.slot===active);if(!p)return;selected=p.kind;moving=p.slot;category=G.kinds[p.kind].category;find('#garden-bubble').hidden=true;drawObjects();drawSpots();drawPalette();announce('帶著'+G.kinds[p.kind].name+'，點亮點搬到新家。');showWorkspace();};
    find('#garden-remove').onclick=()=>{if(active===null)return;remember();setItems(items().filter(p=>p.slot!==active));clearSelection();save();syncStatus();drawSpots();announce('朋友回工具箱休息了，隨時可以請它回來。');};
    find('#garden-listen').onclick=()=>{const p=items().find(p=>p.slot===active);if(p)speak(G.kinds[p.kind].name);};
    find('#garden-care').onclick=()=>{const p=items().find(p=>p.slot===active);if(!p)return;const b=find(`[data-object="${active}"]`);b.classList.remove('cared');void b.offsetWidth;b.classList.add('cared');effect('place');announce(G.kinds[p.kind].category==='plants'?'澆一點水，'+G.kinds[p.kind].name+'向你點點頭！':G.kinds[p.kind].category==='animals'?G.kinds[p.kind].name+'吃飽了，開心地跟你打招呼！':'你放的'+G.kinds[p.kind].name+'真漂亮！');};
    find('#garden-undo').onclick=()=>{if(!undo)return;progress.garden=undo.garden;progress.gardenZones=undo.zones;progress.gardenMemories=undo.memories;progress.weather=undo.weather;area=undo.area;undo=null;drawBackground();clearSelection();save();announce('恢復成剛剛的花園了。');syncStatus();};
    find('#garden-view').onclick=()=>{viewing=!viewing;clearSelection();find('#garden-controls').hidden=viewing;find('#garden-view').textContent=viewing?'✎ 繼續布置':'✦ 欣賞花園';find('#garden-view').setAttribute('aria-pressed',String(viewing));canvas.classList.toggle('admiring',viewing);announce(viewing?'這是你親手布置的小天地！可以拍張照，或點朋友打招呼。':'選個朋友，點亮點或拖過來，繼續布置吧。');};
    find('#garden-ripple').onclick=()=>{canvas.classList.remove('playing-water');void canvas.offsetWidth;canvas.classList.add('playing-water');effect('place');announce('波紋一圈圈散開，和池塘朋友一起玩水！');};
    find('#garden-photo').onclick=()=>{const result=G.takePhoto(progress.gardenAlbum,items(),area,progress.weather);if(!result.ok){announce('相簿有 12 張作品了！先去相簿收起一張，再拍新照片。');find('#garden-photo-panel').hidden=false;find('#garden-album').setAttribute('aria-expanded','true');drawAlbum();return;}progress.gardenAlbum=result.album;if(!progress.gardenMemories.includes('photo'))progress.gardenMemories.push('photo');save();syncStatus();drawAlbum();effect('finish');canvas.classList.remove('photographed');void canvas.offsetWidth;canvas.classList.add('photographed');announce('咔嚓！第 '+progress.gardenAlbum.length+' 張花園照，已放進相簿。');};
    find('#garden-album').onclick=()=>{const open=find('#garden-photo-panel').hidden;find('#garden-photo-panel').hidden=!open;find('#garden-album').setAttribute('aria-expanded',String(open));drawAlbum();if(open)find('#garden-photo-panel').scrollIntoView({block:'start'});};
    find('#garden-photo-undo').onclick=()=>{if(!photoUndo)return;if(progress.gardenAlbum.length>=12){find('#garden-photo-message').textContent='相簿已滿，先收起一張，再復原這張。';return;}progress.gardenAlbum.splice(Math.min(photoUndo.index,progress.gardenAlbum.length),0,photoUndo.photo);photoUndo=null;save();drawAlbum();syncStatus();find('#garden-photo-message').textContent='收起的照片已放回相簿。';};
    panel.addEventListener('pointerdown',e=>{if(viewing||e.isPrimary===false||e.button!==0||e.target.closest('#garden-photo-panel'))return;const b=e.target.closest('[data-decoration],[data-object]');if(!b||b.disabled)return;drag={pointer:e.pointerId,button:b,x:e.clientX,y:e.clientY,kind:b.dataset.kind||b.dataset.decoration,slot:b.dataset.object===undefined?null:Number(b.dataset.object),started:false,before:{selected,moving,active,category}};b.setPointerCapture(e.pointerId);});
    panel.addEventListener('pointermove',e=>{
      if(!drag||e.pointerId!==drag.pointer)return;if(!drag.started&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<10)return;
      if(!drag.started){drag.started=true;selected=drag.kind;moving=drag.slot;active=null;find('#garden-bubble').hidden=true;drawObjects();drawSpots();const ghost=document.createElement('div');ghost.className='garden-drag-ghost';ghost.innerHTML=G.sprite(selected);document.body.append(ghost);drag.ghost=ghost;announce('帶著'+G.kinds[selected].name+'，放到亮點上。');}
      e.preventDefault();drag.ghost.style.left=e.clientX+'px';drag.ghost.style.top=e.clientY+'px';const r=canvas.getBoundingClientRect(),slot=G.nearestSlot(items(),selected,(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100,progress.rounds,area,moving);drag.target=slot;find('#garden-spots').querySelectorAll('[data-slot]').forEach(b=>b.classList.toggle('drop-target',Number(b.dataset.slot)===slot));
    });
    function endDrag(e,cancelled=false){if(!drag||e.pointerId!==drag.pointer)return;const state=drag;drag=null;try{state.button.releasePointerCapture(e.pointerId);}catch{}if(!state.started)return;state.ghost.remove();suppressClick=performance.now()+400;if(!cancelled&&state.target!==null&&state.target!==undefined&&put(state.target))return;({selected,moving,active,category}=state.before);drawObjects();drawSpots();drawPalette();announce('沒放成功，朋友回原位了。也可以選朋友，再點亮點放置。');}
    panel.addEventListener('pointerup',e=>endDrag(e));panel.addEventListener('pointercancel',e=>endDrag(e,true));
    drawBackground();drawObjects();drawSpots();drawPalette();drawAlbum();announce(selected?'拿著：'+G.kinds[selected].name+'。點亮點，讓朋友住進來。':'選朋友點亮點，也可以拖進場景。三個區域都能布置！');window.scrollTo(0,0);if(selected)showWorkspace();
  }
  root.GardenScene={open};
})(window);
